### ISSUE TITLE
Naming of terms

### ISSUE THREAD

**Issue by max-little** [klb2/qmkpy#15]
Although the knapsack problem is well-known, the choice of the terms "profit" is unusual. I would suggest "_value_" instead, because maximizing value under weight constraints is usually how knapsack problems are described.

**Comment by klb2** [comment]
It is correct that many authors use the term "value" instead of "profit". However, the naming "profit" is also not uncommon in the literature on the quadratic multiple knapsack problem, e.g.,
- https://link.springer.com/article/10.1007/s10589-013-9623-y
- https://www.tandfonline.com/doi/full/10.1080/01605682.2020.1843982
- https://www.sciencedirect.com/science/article/abs/pii/S0305054813002244

We therefore stick to the current naming.
